#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Delete certificate authority
  hyperledger.fabric_ansible_collection.certificate_authority:
      state: "{{ state }}"
      api_endpoint: "{{ api_endpoint }}"
      api_authtype: "{{ api_authtype }}"
      api_key: "{{ api_key }}"
      api_secret: "{{ api_secret | default(omit) }}"
      api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
      api_timeout: "{{ api_timeout | default(omit) }}"
      name: "{{ ca_name }}"

- name: Delete certificate authority admin
  hyperledger.fabric_ansible_collection.enrolled_identity:
      state: "{{ state }}"
      api_endpoint: "{{ api_endpoint }}"
      api_authtype: "{{ api_authtype }}"
      api_key: "{{ api_key }}"
      api_secret: "{{ api_secret | default(omit) }}"
      api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
      api_timeout: "{{ api_timeout | default(omit) }}"
      path: "{{ ca_admin_identity }}"

- name: Delete organization admin
  hyperledger.fabric_ansible_collection.enrolled_identity:
      state: "{{ state }}"
      api_endpoint: "{{ api_endpoint }}"
      api_authtype: "{{ api_authtype }}"
      api_key: "{{ api_key }}"
      api_secret: "{{ api_secret | default(omit) }}"
      api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
      api_timeout: "{{ api_timeout | default(omit) }}"
      path: "{{ organization_admin_identity }}"

- name: Delete organization
  hyperledger.fabric_ansible_collection.organization:
      state: "{{ state }}"
      api_endpoint: "{{ api_endpoint }}"
      api_authtype: "{{ api_authtype }}"
      api_key: "{{ api_key }}"
      api_secret: "{{ api_secret | default(omit) }}"
      api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
      api_timeout: "{{ api_timeout | default(omit) }}"
      name: "{{ organization_name }}"

- name: Delete peer
  hyperledger.fabric_ansible_collection.peer:
      state: "{{ state }}"
      api_endpoint: "{{ api_endpoint }}"
      api_authtype: "{{ api_authtype }}"
      api_key: "{{ api_key }}"
      api_secret: "{{ api_secret | default(omit) }}"
      api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
      api_timeout: "{{ api_timeout | default(omit) }}"
      name: "{{ peer_name }}"
  when: peers == 1

- name: Delete multiple peers
  hyperledger.fabric_ansible_collection.peer:
      state: "{{ state }}"
      api_endpoint: "{{ api_endpoint }}"
      api_authtype: "{{ api_authtype }}"
      api_key: "{{ api_key }}"
      api_secret: "{{ api_secret | default(omit) }}"
      api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
      api_timeout: "{{ api_timeout | default(omit) }}"
      name: "{{ peer_name }}{{ item }}"
  loop: "{{ range(1, peers + 1, 1) | list }}"
  when: peers > 1
